document.write("                    <!-- InstanceEndEditable --></td>");
document.write("                  <td width=\"3%\" rowspan=\"2\">&nbsp;</td>");
document.write("                </tr>");
document.write("              </table>");
document.write("            </td>");
document.write("          </tr>");
document.write("          <tr> ");
document.write("            <td colspan=\"2\" align=\"left\" valign=\"top\"><div align=\"left\"></div></td>");
document.write("          </tr>");
document.write("          <tr> ");
document.write("            <td align=\"right\" valign=\"middle\" bgcolor=\"333333\"><div align=\"left\"><font color=\"#FFFFFF\" size=\"1\">Copyright &copy; 2007-2008 All Rights Reserved CSWIM 2008</font></div></td>");
document.write("            <td align=\"right\" valign=\"middle\" bgcolor=\"333333\"><div align=\"right\"><font color=\"#FFFFFF\" size=\"1\">Site Hosted by Hoffman eCommerce Lab, University of Arizona </font>  &nbsp;</div></td>");
document.write("          </tr>");
document.write("        </table>");
document.write("      </td>");
document.write("      <td width=\"1\" bgcolor=\"cccccc\"></td>");
document.write("    </tr>");
document.write("    <tr height=\"1\"> ");
document.write("      <td colspan=\"3\" bgcolor=\"cccccc\"></td>");
document.write("    </tr>");
document.write("  </table>");
document.write("  <br>");
document.write("</div>");
document.write("<div></td>");
document.write("            <td align=\"right\" valign=\"middle\" bgcolor=\"333333\"><div align=\"right\"><font color=\"#FFFFFF\" size=\"1\">Site Hosted by Hoffman eCommerce Lab, University of Arizona </font>  &nbsp;</div></td>");
document.write("          </tr>");
document.write("        </table>");
document.write("      </td>");
document.write("      <td width=\"1\" bgcolor=\"cccccc\"></td>");
document.write("    </tr>");
document.write("    <tr height=\"1\"> ");
document.write("      <td colspan=\"3\" bgcolor=\"cccccc\"></td>");
document.write("    </tr>");
document.write("  </table>");
document.write("  <br>");
document.write("</div>");
document.write("");
document.write("</body>");
document.write("<!-- InstanceEnd --></html>");
