document.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
document.write("<html><!-- InstanceBegin template=\"/Templates/CSWIMTemp.dwt\" codeOutsideHTMLIsLocked=\"false\" -->");
document.write("<head>");
document.write("<!-- InstanceBeginEditable name=\"doctitle\" -->");
document.write("<title>Welcome to CSWIM 2008 Website</title>");
document.write("<!-- InstanceEndEditable --><meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
document.write("<link href=\"site.css\" rel=\"stylesheet\" type=\"text/css\">");
document.write("<script language=\"JavaScript\" type=\"text/JavaScript\">");
document.write("<!--");
document.write("function MM_preloadImages() { //v3.0");
document.write("  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();");
document.write("    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)");
document.write("    if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}");
document.write("}");
document.write("");
document.write("function MM_findObj(n, d) { //v4.01");
document.write("  var p,i,x;  if(!d) d=document; if((p=n.indexOf(\"?\"))>0&&parent.frames.length) {");
document.write("    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}");
document.write("  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];");
document.write("  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);");
document.write("  if(!x && d.getElementById) x=d.getElementById(n); return x;");
document.write("}");
document.write("");
document.write("function MM_swapImgRestore() { //v3.0");
document.write("  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;");
document.write("}");
document.write("");
document.write("function MM_swapImage() { //v3.0");
document.write("  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)");
document.write("   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}");
document.write("}");
document.write("//-->");
document.write("</script>");
document.write("<style type=\"text/css\">");
document.write("<!--");
document.write("body {");
document.write("	background-image: url(images/bg1.gif);");
document.write("}");
document.write(".style1 {");
document.write("	font-size: 24px;");
document.write("	font-weight: bold;");
document.write("}");
document.write(".style6 {font-weight: bold; color: #000000; font-size: 16px;}");
document.write(".style10 {font-size: x-large}");
document.write("-->");
document.write("</style>");
document.write("<!-- InstanceBeginEditable name=\"head\" -->");
document.write("<style type=\"text/css\">");
document.write("<!--");
document.write("p.MsoNormal {");
document.write("margin:0in;");
document.write("margin-bottom:.0001pt;");
document.write("text-align:justify;");
document.write("text-justify:inter-ideograph;");
document.write("font-size:11.0pt;");
document.write("font-family:\"Times New Roman\";");
document.write("}");
document.write(".style11 {color: #000000}");
document.write("-->");
document.write("</style>");
document.write("<!-- InstanceEndEditable -->");
document.write("</head>");
document.write("");
document.write("");
document.write("<body leftmargin=\"0\" topmargin=\"0\" onLoad=\"MM_preloadImages('images/bt_registration_over.gif','images/bt_home_over.gif','images/bt_venuehotel_over.gif','images/bt_keynote_over.gif','images/bt_panel_over.gif','images/bt_committee_over.gif','images/bt_authguide_over.gif','images/bt_submission_over.gif','images/bt_fprogram_over.gif','images/bt_proceedings_over.gif')\">");
document.write("<div align=\"center\">  <table width=\"700\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"ffffff\">");
document.write("    <tr height=\"1\"> ");
document.write("      <td  colspan=\"3\" bgcolor=\"cccccc\"> </td>");
document.write("    </tr>");
document.write("    <tr> ");
document.write("      <td width=\"1\" bgcolor=\"cccccc\"></td>");
document.write("      <td align=\"left\" valign=\"top\"> <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.write("          <tr> ");
document.write("            <td  height=\"1\" colspan=\"2\" bgcolor=\"cccccc\"></td>");
document.write("          </tr>");
document.write("         ");
document.write("          <tr>");
document.write("            <td colspan=\"2\" align=\"left\" valign=\"top\"><p align=\"center\" class=\"style1\">              <span class=\"style10\"><strong> <img src=\"images/Banner.jpg\" width=\"698\" height=\"156\"></strong></span></p>");
document.write("            </td>");
document.write("          </tr>");
document.write("          <tr>");
document.write("            <td colspan=\"2\">");
document.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
                document.write("<tr align=\"left\" valign=\"top\"> ");
document.write("                  <td width=\"7%\" rowspan=\"2\" background=\"images/bg_menu_white.gif\"><table width=\"194\" height=\"199%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("                    <tr>");
document.write("                      <td valign=\"top\" width=\"27\" background=\"image/obj_menu_left2.gif\"><img src=\"images/obj_menu_left1.gif\" width=\"27\" height=\"272\"></td>");
document.write("                      <td valign=\"top\" background=\"image/obj_menu_down2.gif\" width=\"167\"><table width=\"167\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.write("                          <tr>");
document.write("                            <td width=\"167\"><div align=\"right\"></div></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"index.html\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Home','','images/bt_home_over.gif',1)\"><img src=\"images/bt_home.gif\" alt=\"Home\" name=\"Home\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"advcommittee.htm\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('advcommittee','','images/bt_advcommittee_over.gif',1)\"><img src=\"images/bt_advcommittee.gif\" alt=\"Advisory Committee\" name=\"advcommittee\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"pc.htm\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('committee','','images/bt_committee_over.gif',1)\"><img src=\"images/bt_committee.gif\" alt=\"Committee\" name=\"committee\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><div align=\"left\"><a href=\"keynote.htm\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('keynote','','images/bt_keynote_over.gif',1)\"><img src=\"images/bt_keynote.gif\" alt=\"Keynote\" name=\"keynote\" width=\"146\" height=\"28\" border=\"0\"></a></div></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"panel.htm\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Panel','','images/bt_panel_over.gif',1)\"><img src=\"images/bt_panel.gif\" alt=\"Panel\" name=\"Panel\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"open_meeting.htm\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Open_Meeting','','images/bt_openmeeting_over.gif',1)\"><img src=\"images/bt_openmeeting.gif\" alt=\"Open Meeting\" name=\"OpenMeeting\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"author_guidelines.htm\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('AuthorGuide','','images/bt_authguide_over.gif',1)\"><img src=\"images/bt_authguide.gif\" alt=\"Author Guidelines\" name=\"AuthorGuide\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"http://cswim2008.ecom.arizona.edu/system2/openconf.php\" target=\"_blank\" onMouseOver=\"MM_swapImage('system','','images/bt_submission_over.gif',1)\" onMouseOut=\"MM_swapImgRestore()\"><img src=\"images/bt_submission.gif\" alt=\"Submission System\" name=\"system\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"proceedings.htm\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('proceedings','','images/bt_proceedings_over.gif',1)\"><img src=\"images/bt_proceedings.gif\" alt=\"Proceedings\" name=\"proceedings\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"pdf/CSWIM08FinalProgram.pdf\" target=\"_blank\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Final Program','','images/bt_fprogram_over.gif',1)\"><img src=\"images/bt_fprogram.gif\" alt=\"Final Program\" name=\"Final Program\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"venue_hotel.htm\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Venue','','images/bt_venuehotel_over.gif',1)\"><img src=\"images/bt_venuehotel.gif\" alt=\"Venue\" name=\"Venue\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td><a href=\"registration.htm\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('registration','','images/bt_registration_over.gif',1)\"><img src=\"images/bt_registration.gif\" alt=\"Registration\" name=\"registration\" width=\"146\" height=\"28\" border=\"0\"></a></td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td>&nbsp;</td>");
document.write("                          </tr>");
document.write("                          <tr>");
document.write("                            <td>&nbsp;</td>");
document.write("                          </tr>");
document.write("                      </table></td>");
document.write("                    </tr>");
document.write("                    <tr>");
document.write("                      <td colspan=\"2\" valign=\"top\" background=\"images/bg_menu_white.gif\"><table width=\"133\" border=\"0\" align=\"right\">");
document.write("                          <tr>");
document.write("                            <td><div align=\"center\">");
document.write("                              <p class=\"style6\">                                SPONSORS</p>");
document.write("                              </div></td>");
document.write("                          </tr>");

document.write("                          <tr>");
document.write("                            <td><div align=\"center\"><a href=\"http://www.pbc.gov.cn/english/\" target=\"_blank\"><img src=\"images/PBC_logo.jpg\" width=\"101\" height=\"85\" border=\"0\"></a><br>");
document.write("                              People's Bank of China");
document.write("                              <br>");
document.write("                              <br>");
document.write("                            </div></td>");
document.write("                          </tr>");

document.write("                          <tr>");
document.write("                            <td><div align=\"center\"><a href=\"http://www.tsinghua.edu.cn/eng/index.jsp\" target=\"_blank\"><img src=\"images/THU_logo.gif\" width=\"145\" height=\"56\" border=\"0\"></a><br>");
document.write("                              School of Economics and Management<br>");
document.write("                              Tsinghua University");
document.write("                              <br>");
document.write("                              <br>");
document.write("                            </div></td>");
document.write("                          </tr>");

document.write("                          <tr>");
document.write("                            <td><div align=\"center\"><a href=\"http://psweb.swufe.edu.cn/~english/\" target=\"_blank\"><img src=\"images/SWUFE_logo.jpg\" width=\"139\" height=\"93\" border=\"0\"></a><br>");
document.write("                              Southwestern University of Finance and Economics (SWUFE)");
document.write("                              <br>");
document.write("                              <br>");
document.write("                            </div></td>");
document.write("                          </tr>");

document.write("                          <tr>");
document.write("                            <td><div align=\"center\"><a href=\"http://www.ia.ac.cn/new/english/\" target=\"_blank\"><img src=\"images/IAAC_logo.jpg\" width=\"65\" height=\"59\" border=\"0\"></a><br>");
document.write("                              Institute of Automation<br>");
document.write("                              Chinese Academy of Sciences");
document.write("                              <br>");
document.write("                              <br>");
document.write("                            </div></td>");
document.write("                          </tr>");

document.write("                          <tr>");
document.write("                            <td><div align=\"center\"><a href=\"http://cnais.em.tsinghua.edu.cn/cn/\" target=\"_blank\"><img src=\"images/CNAIS_LOGO_small.gif\" width=\"120\" height=\"120\" border=\"0\"></a><br>");
document.write("                              AIS China Chapter");
document.write("                              <br>");
document.write("                              <br>");
document.write("                            </div></td>");
document.write("                          </tr>");

document.write("                          <tr>");
document.write("                            <td><div align=\"center\"><a href=\"http://www.eller.arizona.edu/\" target=\"_blank\"><img src=\"images/eller_logo.gif\" width=\"177\" height=\"60\" border=\"0\"></a><br>");
document.write("                              Eller College of Management<br>");
document.write("                              University of Arizona");
document.write("                              <br>");
document.write("                              <br>");
document.write("                            </div></td>");
document.write("                          </tr>");


document.write("                          <tr>");
document.write("                            <td><div align=\"center\"><a href=\"http://www.informs.org/\" target=\"_blank\"><img src=\"images/informs_logo.gif\" width=\"170\" height=\"83\" border=\"0\"></a><br>");
document.write("                              INFORMS");
document.write("                              <br>");
document.write("                              <br>");
document.write("                            </div></td>");
document.write("                          </tr>");


document.write("                          <tr>");
document.write("                            <td><div align=\"center\"><a href=\"http://citebm.business.uiuc.edu/ebiz/\" target=\"_blank\"><img src=\"images/ais_logo.gif\" width=\"80\" height=\"95\" border=\"0\"></a><br>");
document.write("                              AIS SIGeBIZ");
document.write("                              <br>");
document.write("                              <br>");
document.write("                            </div></td>");
document.write("                          </tr>");


document.write("                          <tr>");
document.write("                            <td><div align=\"center\"><a href=\"http://www.acm.org/press-room/news-releases/acm-china-office/\" target=\"_blank\"><img src=\"images/ACM_logo.jpg\" width=\"123\" height=\"118\" border=\"0\"></a><br>");
document.write("                              ACM Beijing");
document.write("                              <br>");
document.write("                              <br>");
document.write("                            </div></td>");
document.write("                          </tr>");


document.write("                          <tr>");
document.write("                            <td><div align=\"center\"><a href=\"http://www.ieeesmc.org/index.html\" target=\"_blank\"><img src=\"images/ieee_logo.gif\" width=\"157\" height=\"87\" border=\"0\"></a><br>");
document.write("                              IEEE SMC");
document.write("                              <br>");
document.write("                              <br>");
document.write("                            </div></td>");
document.write("                          </tr>");


document.write("                        </table>                        ");
document.write("                        <p>&nbsp;</p>");
document.write("                        <p>&nbsp;</p>");
document.write("                        <p>&nbsp;</p>");
document.write("                        <p>&nbsp;</p>");
document.write("                        </td>");
document.write("                      </tr>");
document.write("                  </table></td>");
document.write("                  <td width=\"90%\"><!-- InstanceBeginEditable name=\"Content\" -->");
